name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCfDkQiPchwM0F2SkHWl5JYQ
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_BIGSIS }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_BIGSIS }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`Bigsis 빅씨스 - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
