name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCoe-0EVDJnjlSoPK8ygcGwQ
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_GYMJONGKOOK }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_GYMJONGKOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`GYM JONG KOOK 김종국 - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
